### ISSUE TITLE
Install CLI using homebrew

### ISSUE THREAD

**Issue by conneryn** [c6o/roadmap#20]
### Overview

Not all development teams work in a node environment and/or want to deal with NPM.  Not to mention, relying on NPM for globally installed packages can become quite complicated when using tools like NVM to jump around between versions.

Additionally, if we want to deliver standalone binaries, or move away from NodeJS altogether, it 

Homebrew, on the other hand, is a language agnostic package management tool that has become quite popular for Mac (and increasingly Linux) users. 

### Goal

Allow users to install and update the CLI using `brew install`.

### Tasks

- [x] Create homebrew tap
- [x] Create czctl formula
- [ ] Test and validate installation on different systems
- [ ] Update documentation
